version: '3.5'
services:
  db:
    image: mongo
    ports:
      - 27017:27017
  
  authapi:
    image: authapi
    ports:
      - 7000:7000
    environment:
      MONGODB_SERVER: "mongodb://127.0.0.1:27017/AuthDB"
      
  favapi:
    image: favapi
    ports:
      - 2000:2000
    environment:
      MONGODB_SERVER: "mongodb://127.0.0.1:27017/favouritesDB"
  
  newsapi:
    image: newsapi
    ports:
      - 8000:8000
  
  newsapp:
    image: newsapp
    ports:
      - 9000:80